include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    omit_local_variable_types: false
    always_use_package_imports: false
    always_put_required_named_parameters_first: false